### PR TITLE
[#7] Remove `dist/` from repo

### PR DESCRIPTION
**Pull request by pmeinhardt**
- Remove compiled files from `dist/`
- Always clean the build directory
- Generate source-maps when building
- Build on install

### CODE REVIEW

**Comment by pmeinhardt** [comment]
@tessi can you check whether this works in the project that you've used it in?
Temporarily witching to `bitcrowd/tickety-tick-formatter#feature/7-remove-dist-from-repo` should do the trick (see also https://github.com/bitcrowd/tickety-tick/pull/300).

I had to `rm -rf node_modules` before running `npm install` or `yarn install` again.

**Comment by pmeinhardt** [comment]
After looking at it I think we should create package releases indeed and push them to a registry (GitHub or npm), like @klappradla [suggested](https://github.com/bitcrowd/tickety-tick-formatter/issues/7#issuecomment-831995101). 💚 

We can probably create some automation for this, to remove overhead.

**Comment by tessi** [comment]
👍 for putting releases up. it's probably a more manageable way to handle updated of this dependency

**Comment by pmeinhardt** [comment]
Closing, as we'll be deprecating this repo. See #9. 👋

**Pull request closed without merging**
